name: chesel
description: Master Component & Microcopy Blueprint - Cross Platform App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  fonts:
    - family: LibreBaskerville
      fonts:
        - asset: assets/fonts/LibreBaskerville-Regular.ttf
        - asset: assets/fonts/LibreBaskerville-Bold.ttf
          weight: 700
        - asset: assets/fonts/LibreBaskerville-Italic.ttf
          style: italic
    
    - family: IMFellEnglishSC
      fonts:
        - asset: assets/fonts/IMFellEnglishSC-Regular.ttf

  assets:
    - assets/images/
    - assets/animations/